import {secretKey} from "./access.ts";

type ToolRisk = "low" | "medium" | "high";
type ToolDefinition = {
  name:string;
  description:string;
  category:"system"|"data"|"communication"|"integration"|"development";
  risk:ToolRisk;
  requires_confirmation:boolean;
  server_only:boolean;
  input_schema:Record<string,unknown>;
};

export const TOOL_REGISTRY:ToolDefinition[]=[
  {name:"get_time",description:"Текущая дата и время сервера",category:"system",risk:"low",requires_confirmation:false,server_only:true,input_schema:{type:"object",properties:{}}},
  {name:"calculator",description:"Безопасный калькулятор арифметических выражений",category:"system",risk:"low",requires_confirmation:false,server_only:true,input_schema:{type:"object",properties:{expression:{type:"string"}},required:["expression"]}},
  {name:"weather",description:"Текущая погода по городу",category:"system",risk:"low",requires_confirmation:false,server_only:true,input_schema:{type:"object",properties:{city:{type:"string"}},required:["city"]}},
  {name:"wikipedia",description:"Краткая справка из Википедии",category:"system",risk:"low",requires_confirmation:false,server_only:true,input_schema:{type:"object",properties:{query:{type:"string"},lang:{type:"string"}},required:["query"]}},
  {name:"supabase",description:"Работа с бизнес-данными Supabase через серверные полномочия",category:"data",risk:"medium",requires_confirmation:false,server_only:true,input_schema:{type:"object",properties:{action:{type:"string"},table:{type:"string"},query:{type:"string"},body:{type:"object"}},required:["action"]}},
  {name:"find_records",description:"Найти записи в разрешенной бизнес-таблице Supabase",category:"data",risk:"medium",requires_confirmation:false,server_only:true,input_schema:{type:"object",properties:{table:{type:"string"},query:{type:"string"},limit:{type:"integer"}},required:["table"]}},
  {name:"create_record",description:"Создать запись в разрешенной бизнес-таблице Supabase",category:"data",risk:"medium",requires_confirmation:false,server_only:true,input_schema:{type:"object",properties:{table:{type:"string"},body:{type:"object"}},required:["table","body"]}},
  {name:"update_records",description:"Обновить записи в разрешенной бизнес-таблице Supabase по фильтру",category:"data",risk:"high",requires_confirmation:true,server_only:true,input_schema:{type:"object",properties:{table:{type:"string"},query:{type:"string"},body:{type:"object"}},required:["table","query","body"]}},
  {name:"count_records",description:"Посчитать записи в разрешенной бизнес-таблице Supabase",category:"data",risk:"low",requires_confirmation:false,server_only:true,input_schema:{type:"object",properties:{table:{type:"string"},query:{type:"string"}},required:["table"]}},
  {name:"github",description:"Работа с GitHub через серверный токен без удаления файлов",category:"development",risk:"high",requires_confirmation:true,server_only:true,input_schema:{type:"object",properties:{action:{type:"string"},repo:{type:"string"},path:{type:"string"},content:{type:"string"},sha:{type:"string"}},required:["action"]}},
  {name:"telegram",description:"Вызов Telegram Bot API через серверный токен",category:"communication",risk:"medium",requires_confirmation:false,server_only:true,input_schema:{type:"object",properties:{method:{type:"string"},params:{type:"object"}},required:["method"]}},
  {name:"telegram_resources",description:"Показать подключенные Telegram-ресурсы пользователя без chat_id",category:"communication",risk:"low",requires_confirmation:false,server_only:true,input_schema:{type:"object",properties:{query:{type:"string"}},required:[]}},{name:"telegram_last_chat",description:"Получить последний chat_id Telegram, полученный через подключенный webhook",category:"communication",risk:"low",requires_confirmation:false,server_only:true,input_schema:{type:"object",properties:{}}},
  {name:"telegram_send_message",description:"Отправить сообщение в Telegram",category:"communication",risk:"medium",requires_confirmation:false,server_only:true,input_schema:{type:"object",properties:{target:{type:"string",description:"Название, username или внутренний идентификатор Telegram-ресурса"},chat_id:{type:["string","number"]},text:{type:"string"},parse_mode:{type:"string"}},required:["text"]}},
  {name:"telegram_send_document",description:"Отправить документ в Telegram по URL",category:"communication",risk:"medium",requires_confirmation:false,server_only:true,input_schema:{type:"object",properties:{target:{type:"string",description:"Название, username или внутренний идентификатор Telegram-ресурса"},chat_id:{type:["string","number"]},document:{type:"string"},caption:{type:"string"}},required:["document"]}},
  {name:"http_request",description:"Безопасный HTTPS-запрос к внешнему бизнес-API",category:"integration",risk:"medium",requires_confirmation:false,server_only:true,input_schema:{type:"object",properties:{method:{type:"string"},url:{type:"string"},headers:{type:"object"},query:{type:"object"},body:{type:["object","array","string","number","boolean","null"]},timeout_ms:{type:"integer"}},required:["method","url"]}},
  {name:"file_read_text",description:"Обязательно используй этот инструмент, когда пользователь просит прочитать, получить, пересказать или проанализировать содержимое файла по HTTPS URL (включая raw.githubusercontent.com). Инструмент возвращает содержимое файла для дальнейшего анализа.",category:"data",risk:"low",requires_confirmation:false,server_only:true,input_schema:{type:"object",properties:{url:{type:"string"},max_chars:{type:"integer"}},required:["url"]}},
  {name:"csv_parse",description:"Разобрать CSV-текст в заголовки и строки",category:"data",risk:"low",requires_confirmation:false,server_only:true,input_schema:{type:"object",properties:{csv:{type:"string"},delimiter:{type:"string"}},required:["csv"]}},
  {name:"web_search",description:"Поиск актуальной информации в интернете с возвратом источников",category:"integration",risk:"low",requires_confirmation:false,server_only:true,input_schema:{type:"object",properties:{query:{type:"string"},limit:{type:"integer"}},required:["query"]}},
  {name:"send_email",description:"Отправить email через настроенный почтовый сервис",category:"communication",risk:"medium",requires_confirmation:true,server_only:true,input_schema:{type:"object",properties:{to:{type:"string"},subject:{type:"string"},text:{type:"string"},from:{type:"string"}},required:["to","subject","text"]}}
];

export const serverTools:any[]=TOOL_REGISTRY.map(t=>({type:"function",function:{name:t.name,description:t.description,parameters:t.input_schema}}));
export const serverToolNames=new Set(TOOL_REGISTRY.map(t=>t.name));
export const toolRegistryByName=new Map(TOOL_REGISTRY.map(t=>[t.name,t]));

const calc=(v:string)=>{const e=String(v).replace(/\^/g,"**");if(!/^[0-9+\-*/().,%\s*]+$/.test(e))throw new Error("invalid_expression");return String(Function('"use strict";return ('+e.replace(/,/g,".")+')')())};
async function j(u:string){const r=await fetch(u);if(!r.ok)throw new Error("tool_http");return r.json()}
async function resolveTelegramTarget(target:string,opts:{agentKey?:string,userId?:string|null}){const url=Deno.env.get("SUPABASE_URL"),key=secretKey();if(!url||!key)throw new Error("supabase_config");const v=String(target||"").trim();if(!v)throw new Error("telegram_target_missing");const owner=opts.userId===null||opts.userId===undefined?"null":encodeURIComponent(String(opts.userId));const q="/rest/v1/agent_resources?user_id=eq."+owner+"&resource_type=eq.telegram_chat&status=eq.active&select=external_id,name,username,metadata&or=(external_id.eq."+encodeURIComponent(v)+",name.ilike."+encodeURIComponent("*"+v+"*")+",username.ilike."+encodeURIComponent("*"+v.replace(/^@/,"")+"*")+")&limit=5";const r=await fetch(url+q,{headers:{apikey:key,Authorization:"Bearer "+key}});if(!r.ok)throw new Error("telegram_resource_lookup_failed");const rows=await r.json();if(rows.length===1)return rows[0].external_id;if(rows.length>1)throw new Error("telegram_target_ambiguous");throw new Error("telegram_target_not_found")}
const b64=(s:string)=>{const bytes=new TextEncoder().encode(s);let bin="";for(const b of bytes)bin+=String.fromCharCode(b);return btoa(bin)};

export async function executeTool(name:string,args:any,opts:{telegramToken?:string,agentKey?:string,userId?:string|null}={}){
  switch(name){
    case"get_time":return new Date().toLocaleString("ru-RU",{dateStyle:"full",timeStyle:"short"});
    case"calculator":return calc(args.expression);
    case"weather":{const g=await j("https://geocoding-api.open-meteo.com/v1/search?count=1&language=ru&name="+encodeURIComponent(args.city));if(!g.results?.length)return"Город не найден";const c=g.results[0],w=await j(`https://api.open-meteo.com/v1/forecast?latitude=${c.latitude}&longitude=${c.longitude}&current=temperature_2m,apparent_temperature,wind_speed_10m,precipitation`);return JSON.stringify({город:c.name,страна:c.country,...w.current})}
    case"wikipedia":{const l=args.lang==="en"?"en":"ru";const s=await j(`https://${l}.wikipedia.org/w/api.php?action=query&list=search&srlimit=1&format=json&origin=*&srsearch=`+encodeURIComponent(args.query));const t=s.query?.search?.[0]?.title;if(!t)return"Ничего не найдено";const x=await j(`https://${l}.wikipedia.org/api/rest_v1/page/summary/`+encodeURIComponent(t));return t+": "+x.extract}
    case"supabase":{const table=String(args.table||"");if(!/^agent_[a-z0-9_]+$/.test(table)&&table!=="admin_users")throw new Error("table_forbidden");const action=String(args.action||"read").toLowerCase();if(!["read","insert","update"].includes(action))throw new Error("action_forbidden");const url=Deno.env.get("SUPABASE_URL"),key=secretKey(),path="/rest/v1/"+table+(args.query?"?"+args.query:"");const init:any={method:action==="read"?"GET":action==="insert"?"POST":"PATCH",headers:{apikey:key,"Content-Type":"application/json",Prefer:"return=representation"}};if(action!=="read")init.body=JSON.stringify(args.body||{});const r=await fetch(url+path,init),txt=await r.text();if(!r.ok)throw new Error("supabase_tool_error");return txt.slice(0,8000)}
    case"file_read_text":{const raw=String(args.url||"");let u:URL;try{u=new URL(raw)}catch{throw new Error("file_url_invalid")}if(u.protocol!=="https:")throw new Error("file_https_required");const r=await fetch(u);if(!r.ok)throw new Error("file_fetch_failed");const ct=r.headers.get("content-type")||"";if(!/(text|json|csv|xml|javascript|typescript)/i.test(ct)&&!/[.]((txt)|(csv)|(json)|(md))$/i.test(u.pathname))throw new Error("file_type_unsupported");const max=Math.min(Math.max(Number(args.max_chars)||20000,1000),50000);return (await r.text()).slice(0,max)}
    case"csv_parse":{const csv=String(args.csv||"");const d=String(args.delimiter||",");const rows:string[][]=[];let row:string[]=[],cell="",quote=false;for(let i=0;i<csv.length;i++){const ch=csv[i];if(ch==='"'&&csv[i+1]==='"'&&quote){cell+='"';i++;continue}if(ch==='"'){quote=!quote;continue}if(ch===d&&!quote){row.push(cell);cell="";continue}if((ch==='\n'||ch==='\r')&&!quote){if(ch==='\\r'&&csv[i+1]==='\\n')i++;row.push(cell);cell="";if(row.some(v=>v!==""))rows.push(row);row=[];continue}cell+=ch}row.push(cell);if(row.some(v=>v!==""))rows.push(row);const headers=rows.shift()||[];return JSON.stringify({headers,rows:rows.slice(0,500),total_rows:rows.length})}
    case"web_search":{const q=encodeURIComponent(String(args.query||""));if(!q)throw new Error("search_query_missing");const limit=Math.min(Math.max(Number(args.limit)||5,1),10);const r=await fetch("https://html.duckduckgo.com/html/?q="+q,{headers:{"User-Agent":"Mozilla/5.0 my-agent"}});if(!r.ok)throw new Error("search_failed");const html=await r.text();const out:any[]=[];const re=/<a[^>]*class="result__a"[^>]*href="([^"]+)"[^>]*>([^<]*)<\/a>/gi;let m;while((m=re.exec(html))&&out.length<limit){const title=m[2].replace(/<[^>]+>/g,"").replace(/&amp;/g,"&").trim();out.push({title,url:m[1]})}return JSON.stringify({query:String(args.query),results:out})}
    case"send_email":{const token=Deno.env.get("RESEND_API_KEY");const from=String(args.from||Deno.env.get("EMAIL_FROM")||"");if(!token||!from)throw new Error("email_not_configured");const r=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:"Bearer "+token,"Content-Type":"application/json"},body:JSON.stringify({from,to:String(args.to||""),subject:String(args.subject||"").slice(0,200),text:String(args.text||"").slice(0,20000)})});const txt=await r.text();if(!r.ok)throw new Error("email_send_failed");return txt.slice(0,4000)}
    case"telegram_resources":{const url=Deno.env.get("SUPABASE_URL"),key=secretKey();if(!url||!key)throw new Error("supabase_config");const owner=opts.userId===null||opts.userId===undefined?"null":encodeURIComponent(String(opts.userId));const q=String(args.query||"").trim();let path="/rest/v1/agent_resources?user_id=eq."+owner+"&resource_type=eq.telegram_chat&status=eq.active&select=external_id,name,username,metadata,last_seen_at&order=last_seen_at.desc&limit=50";if(q)path+="&or=(name.ilike."+encodeURIComponent("*"+q+"*")+",username.ilike."+encodeURIComponent("*"+q.replace(/^@/,"")+"*")+",external_id.eq."+encodeURIComponent(q)+")";const r=await fetch(url+path,{headers:{apikey:key,Authorization:"Bearer "+key}});if(!r.ok)throw new Error("telegram_resource_lookup_failed");return JSON.stringify(await r.json())},case"telegram_last_chat":{const url=Deno.env.get("SUPABASE_URL"),key=secretKey();if(!url||!key)throw new Error("supabase_config");const r=await fetch(url+"/rest/v1/agent_telegram_chats?select=chat_id,chat_type,username,first_name,last_name,last_message_text,last_seen_at&order=last_seen_at.desc&limit=1",{headers:{apikey:key,Authorization:"Bearer "+key}});const txt=await r.text();if(!r.ok)throw new Error("telegram_chat_lookup_failed");const rows=JSON.parse(txt);return JSON.stringify(rows[0]||{chat_id:null,message:"Через подключенный webhook Telegram-чат пока не получен"});}
    case"telegram_send_message":{const token=String(opts.telegramToken||Deno.env.get("TELEGRAM_BOT_TOKEN")||"");if(!token)throw new Error("telegram_secret_missing");const chat_id=args.chat_id!==undefined?args.chat_id:await resolveTelegramTarget(args.target,opts);if(!args.text)throw new Error("telegram_args_missing");const r=await fetch("https://api.telegram.org/bot"+token+"/sendMessage",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({chat_id,text:String(args.text).slice(0,4000),...(args.parse_mode?{parse_mode:String(args.parse_mode)}:{})})});const txt=await r.text();if(!r.ok)throw new Error("telegram_send_failed");return txt.slice(0,6000)}
    case"telegram_send_document":{const token=String(opts.telegramToken||Deno.env.get("TELEGRAM_BOT_TOKEN")||"");if(!token)throw new Error("telegram_secret_missing");const chat_id=args.chat_id!==undefined?args.chat_id:await resolveTelegramTarget(args.target,opts);if(!args.document)throw new Error("telegram_args_missing");const r=await fetch("https://api.telegram.org/bot"+token+"/sendDocument",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({chat_id,document:String(args.document),...(args.caption?{caption:String(args.caption).slice(0,1000)}:{})})});const txt=await r.text();if(!r.ok)throw new Error("telegram_send_failed");return txt.slice(0,6000)}
    case"find_records":case"create_record":case"update_records":case"count_records":{const table=String(args.table||"");if(!/^agent_[a-z0-9_]+$/.test(table))throw new Error("table_forbidden");const action=name==="find_records"?"read":name==="create_record"?"insert":name==="update_records"?"update":"count";const url=Deno.env.get("SUPABASE_URL"),key=secretKey();if(!url||!key)throw new Error("supabase_config");let path="/rest/v1/"+table;const query=String(args.query||"");if(action==="count"){path+="?"+(query?query+"&":"")+"select=*";const r=await fetch(url+path,{headers:{apikey:key,Authorization:"Bearer "+key,Prefer:"count=exact"}});if(!r.ok)throw new Error("supabase_tool_error");const range=r.headers.get("content-range")||"";const total=range.includes("/")?range.split("/")[1]:"0";return JSON.stringify({count:total})}if(query)path+="?"+query;if(action==="read"){const limit=Math.min(Math.max(Number(args.limit)||50,1),100);path+=(path.includes("?")?"&":"?")+"limit="+limit;const r=await fetch(url+path,{headers:{apikey:key,Authorization:"Bearer "+key}});const txt=await r.text();if(!r.ok)throw new Error("supabase_tool_error");return txt.slice(0,12000)}const r=await fetch(url+path,{method:action==="insert"?"POST":"PATCH",headers:{apikey:key,Authorization:"Bearer "+key,"Content-Type":"application/json",Prefer:"return=representation"},body:JSON.stringify(args.body||{})});const txt=await r.text();if(!r.ok)throw new Error("supabase_tool_error");return txt.slice(0,12000)}
    case"github":{const token=Deno.env.get("GITHUB_TOKEN");if(!token)throw new Error("github_secret_missing");const repo=String(args.repo||"Republic-585/my-agent"),path=String(args.path||""),base="https://api.github.com/repos/"+repo,h={Authorization:"Bearer "+token,Accept:"application/vnd.github+json","X-GitHub-Api-Version":"2026-03-10"},action=String(args.action||"").toLowerCase();if(action==="list")return JSON.stringify(await(await fetch("https://api.github.com/user/repos?sort=updated&per_page=30",{headers:h})).json());if(action==="get_file"){const r=await fetch(base+"/contents/"+path,{headers:h}),x=await r.json();return r.ok?JSON.stringify({path:x.path,sha:x.sha,content:x.content?atob(String(x.content).replace(/\n/g,"")):""}):"GitHub error"}if(action==="put_file"){if(!path||!args.content)throw new Error("missing_file");const r=await fetch(base+"/contents/"+path,{method:"PUT",headers:{...h,"Content-Type":"application/json"},body:JSON.stringify({message:"agent update "+path,content:b64(String(args.content)),...(args.sha?{sha:args.sha}:{})})});const x=await r.json();if(!r.ok)throw new Error("github_write_failed");return JSON.stringify({ok:true,path:x.content?.path,sha:x.content?.sha})}if(action==="status"){const r=await fetch("https://api.github.com/repos/"+repo+"/actions/runs?per_page=3",{headers:h});return JSON.stringify(await r.json())}throw new Error("github_action_forbidden")}
    case"telegram":{const token=String(opts.telegramToken||Deno.env.get("TELEGRAM_BOT_TOKEN")||"");if(!token)throw new Error("telegram_secret_missing");const method=String(args.method||"getMe");if(/^(delete|ban|restrict|leave|refund|unban)/i.test(method))throw new Error("telegram_action_forbidden");const r=await fetch("https://api.telegram.org/bot"+token+"/"+method,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(args.params||{})});return(await r.text()).slice(0,6000)}
    case"http_request":{const method=String(args.method||"GET").toUpperCase();if(!["GET","POST","PUT","PATCH","DELETE"].includes(method))throw new Error("http_method_forbidden");const raw=String(args.url||"");let u:URL;try{u=new URL(raw)}catch{throw new Error("http_url_invalid")}if(u.protocol!=="https:")throw new Error("http_https_required");const host=u.hostname.toLowerCase();if(host==="localhost"||host.endsWith(".localhost")||host==="metadata.google.internal"||host==="169.254.169.254"||/^(10\.|127\.|169\.254\.|192\.168\.|172\.(1[6-9]|2\d|3[0-1])\.)/.test(host)||host==="0.0.0.0")throw new Error("http_private_host");const q=args.query&&typeof args.query==="object"?args.query:{};for(const [k,v] of Object.entries(q))u.searchParams.set(k,String(v));const headers:any={"Accept":"application/json","User-Agent":"my-agent/1.0",...(args.headers&&typeof args.headers==="object"?args.headers:{})};delete headers.host;delete headers["content-length"];const timeout=Math.min(Math.max(Number(args.timeout_ms)||15000,1000),30000);const ac=new AbortController();const timer=setTimeout(()=>ac.abort(),timeout);let r:Response;try{r=await fetch(u,{method,headers,signal:ac.signal,body:["GET","DELETE"].includes(method)?undefined:(typeof args.body==="string"?args.body:args.body==null?undefined:JSON.stringify(args.body))})}catch(e){clearTimeout(timer);throw new Error(e instanceof DOMException&&e.name==="AbortError"?"http_timeout":"http_network_error")}clearTimeout(timer);const txt=(await r.text()).slice(0,12000);return JSON.stringify({status:r.status,ok:r.ok,url:u.toString(),body:txt})}
    default:throw new Error("unknown_server_tool")
  }
}