drop policy if exists agent_profiles_select_own on public.agent_profiles;drop policy if exists agent_profiles_insert_own on public.agent_profiles;drop policy if exists agent_profiles_update_own on public.agent_profiles;
create policy agent_profiles_select_own on public.agent_profiles for select to authenticated using((select auth.uid())=user_id);
create policy agent_profiles_insert_own on public.agent_profiles for insert to authenticated with check((select auth.uid())=user_id);
create policy agent_profiles_update_own on public.agent_profiles for update to authenticated using((select auth.uid())=user_id) with check((select auth.uid())=user_id);
drop policy if exists agent_conversations_select_own on public.agent_conversations;drop policy if exists agent_conversations_insert_own on public.agent_conversations;drop policy if exists agent_conversations_update_own on public.agent_conversations;drop policy if exists agent_conversations_delete_own on public.agent_conversations;
create policy agent_conversations_select_own on public.agent_conversations for select to authenticated using((select auth.uid())=user_id);
create policy agent_conversations_insert_own on public.agent_conversations for insert to authenticated with check((select auth.uid())=user_id);
create policy agent_conversations_update_own on public.agent_conversations for update to authenticated using((select auth.uid())=user_id) with check((select auth.uid())=user_id);
create policy agent_conversations_delete_own on public.agent_conversations for delete to authenticated using((select auth.uid())=user_id);
drop policy if exists agent_messages_select_own on public.agent_messages;drop policy if exists agent_messages_insert_own on public.agent_messages;drop policy if exists agent_messages_delete_own on public.agent_messages;
create policy agent_messages_select_own on public.agent_messages for select to authenticated using(exists(select 1 from public.agent_conversations c where c.id=conversation_id and c.user_id=(select auth.uid())));
create policy agent_messages_insert_own on public.agent_messages for insert to authenticated with check(exists(select 1 from public.agent_conversations c where c.id=conversation_id and c.user_id=(select auth.uid())));
create policy agent_messages_delete_own on public.agent_messages for delete to authenticated using(exists(select 1 from public.agent_conversations c where c.id=conversation_id and c.user_id=(select auth.uid())));
drop policy if exists agent_memories_select_own on public.agent_memories;drop policy if exists agent_memories_insert_own on public.agent_memories;drop policy if exists agent_memories_update_own on public.agent_memories;drop policy if exists agent_memories_delete_own on public.agent_memories;
create policy agent_memories_select_own on public.agent_memories for select to authenticated using((select auth.uid())=user_id);
create policy agent_memories_insert_own on public.agent_memories for insert to authenticated with check((select auth.uid())=user_id);
create policy agent_memories_update_own on public.agent_memories for update to authenticated using((select auth.uid())=user_id) with check((select auth.uid())=user_id);
create policy agent_memories_delete_own on public.agent_memories for delete to authenticated using((select auth.uid())=user_id);
drop policy if exists agent_payment_orders_select_own on public.agent_payment_orders;
create policy agent_payment_orders_select_own on public.agent_payment_orders for select to authenticated using((select auth.uid())=user_id);